table static_visit_amount_rolling_bucket
	lineageTag: 9a81350b-73bd-41e5-b04b-e5a5cd0ea249

	column visit_amount_rolling_bucket
		dataType: string
		lineageTag: 89db5ac0-9cda-40a0-ac54-ef228fa41c50
		summarizeBy: none
		sourceColumn: visit_amount_rolling_bucket
		sortByColumn: visit_amount_rolling_bucket_sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column visit_amount_rolling_bucket_sort
		dataType: int64
		formatString: 0
		lineageTag: acc55599-dc25-45b1-b60f-50e875f4fa8b
		summarizeBy: none
		sourceColumn: visit_amount_rolling_bucket_sort

		annotation SummarizationSetBy = Automatic

	partition static_visit_amount_rolling_bucket = m
		mode: import
		queryGroup: 'Static Tables'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wiik1MDBONvRW0lEyVIrViVYy9NY1NABxjSBcA29dUzDfGMwHsoHyYAETqAKwCrCIKVQJSI0vkG8GUeGrDWSbg9l++SUKjsXFmel5qSlAQQul2FgA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [visit_amount_rolling_bucket = _t, visit_amount_rolling_bucket_sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"visit_amount_rolling_bucket", type text}, {"visit_amount_rolling_bucket_sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

