table date
	lineageTag: 6092267e-5693-46e2-811d-03732d9b1f3d

	column month_of_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 92f7809e-e7c3-4b23-a29c-53d65e1177cf
		summarizeBy: none
		sourceColumn: month_of_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column month
		dataType: double
		lineageTag: e95392b9-2629-49a8-a23d-23f8fc9b53bf
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column year
		dataType: string
		lineageTag: 32843086-a84e-42f5-9eed-cde2426b19e5
		summarizeBy: none
		sourceColumn: year

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column month_of_year
		dataType: string
		lineageTag: b54bf610-b0c2-49a1-ba8b-5f431948908b
		summarizeBy: none
		sourceColumn: month_of_year
		sortByColumn: month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column updated_on
		dataType: dateTime
		formatString: General Date
		lineageTag: fee44e64-65e4-4915-b561-c2a81c4c823c
		summarizeBy: none
		sourceColumn: updated_on

		annotation SummarizationSetBy = Automatic

	column month_year
		dataType: dateTime
		formatString: mmm-yyyy
		lineageTag: 51ed78e7-65b8-488b-9100-42b9d57091ea
		summarizeBy: none
		sourceColumn: month_year

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column last_year_comparision_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 16b9fbbf-6c89-4577-8878-f141c66600c4
		summarizeBy: none
		sourceColumn: last_year_comparision_flag

		annotation SummarizationSetBy = Automatic

	partition date = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(DB_HOST_STRING,WAREHOUSE,[Role=ROLE]),
				    DAP_Database = Source{[Name=L5_DB_NAME,Kind="Database"]}[Data],
				    L5_Schema = DAP_Database{[Name=SCHEMA_NAME,Kind="Schema"]}[Data],
				    DATE_VIEW_View = L5_Schema{[Name="DATE_VIEW",Kind="View"]}[Data],
				    #"Lowercased Text" = Table.TransformColumnNames(DATE_VIEW_View, Text.Lower),
				    #"Added Custom" = Table.AddColumn(#"Lowercased Text", "Custom", each Text.Combine({[month_of_year], Number.ToText([year], "G")}, "-")),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom",{{"Custom", "month_year"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"updated_key"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

